name: music_sharity
description: "Share music across all platforms"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  share_plus: ^12.0.1
  app_links: ^7.0.0
  receive_sharing_intent: 1.8.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  web: ^1.1.1
  shared_preferences: ^2.5.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/platforms/
    - assets/images/brandings/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/brandings/logo.png"

  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/brandings/logo.png"

  image_path_ios: "assets/images/brandings/logo.png"
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/images/brandings/logo.png"
    background_color: "#0A0A0A"
    theme_color: "#00A8FF"

  windows:
    generate: true
    image_path: "assets/images/brandings/logo.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/images/brandings/logo.png"

  linux:
    generate: true
    image_path: "assets/images/brandings/logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: true

  fullscreen: true
  color: "#0A0A0A"
  image: assets/images/brandings/logo.png

  android_12:
    image: assets/images/brandings/logo-splash.png
    icon_background_color: "#0A0A0A"
    color: "#0A0A0A"
